# Make sure to install swi-prolog-full on Ubuntu to have all dependencies.
ADGLibToolkit: ADGLibToolkit.pl
	swipl -o ADGLibToolkit -t run -c ADGLibToolkit.pl --stand_alone=true

clean:
	rm -f ADGLibToolkit

.PHONY: clean
