% ------------  TPTP/fof translation by Predrag Janicic, 2025.  ------------
% Input: tmp_2_thm_0255_Example55.p; Output: thm_0255_Example55.p; Arg: [-p]

include('geo.ax').
fof(thm, conjecture, ! [ A,B,C] : ((
   dimensions(130, 110)
   & freepoint(A, 20, 20)
   & freepoint(B, 110, 20)
   & freepoint(C, 80, 90)
   & collinear(M, A, B)
   & collinear(N, B, C)
   & collinear(P, A, C)
   & parallel(P1, P, A, B)
   & parallel(P2, N, A, C)
   & parallel(P3, M, B, C)
   & intersection(P1, P, B, C, P_1)
   & intersection(P3, M, A, C, M_1)
   & intersection(P2, N, A, B, N_1)
   & cmark_b(A)
   & cmark_b(B)
   & cmark_t(C)
   & cmark_rt(N)
   & cmark_b(M)
   & cmark_lt(P)
   & cmark_rt(P_1)
   & cmark_b(N_1)
   & cmark_lt(M_1)
   & drawsegment(A, B)
   & drawsegment(A, C)
   & drawsegment(C, B)
   & drawsegment(P, P_1)
   & drawsegment(M, M_1)
   & drawsegment(N, N_1)
   & drawdashsegment(M, N)
   & drawdashsegment(M, P)
   & drawdashsegment(P, N)
   & drawdashsegment(M_1, N_1)
   & drawdashsegment(M_1, P_1)
   & drawdashsegment(P_1, N_1)
   & prooflevel(1)) 
 => 
   signed_area3(M, N, P) = signed_area3(M_1, N_1, P_1))).
