% ------------  TPTP/fof translation by Predrag Janicic, 2025.  ------------
% Input: tmp_2_thm_0203_Example3.p; Output: thm_0203_Example3.p; Arg: [-p]

include('geo.ax').
fof(thm, conjecture, ! [ A,B,D,E] : ((
   dimensions(100, 100)
   & freepoint(A, 20, 20)
   & freepoint(B, 55, 20)
   & collinear(C, A, B)
   & freepoint(D, 40.2, 47.2)
   & freepoint(E, 53.3, 37.5)
   & intersection(A, E, C, D, J)
   & intersection(A, D, B, E, G)
   & intersection(B, D, E, C, K)
   & intersection(A, E, B, D, I)
   & intersection(C, D, B, E, L)
   & intersection(E, C, A, D, H)
   & intersection(D, E, A, B, F)
   & intersection(J, H, I, G, O)
   & cmark_rb(A)
   & cmark_b(B)
   & cmark_lb(C)
   & cmark_t(D)
   & cmark_rb(E)
   & cmark_lb(J)
   & cmark_lt(G)
   & cmark_r(K)
   & cmark_b(I)
   & cmark_r(L)
   & cmark_rb(H)
   & cmark_b(F)
   & cmark_r(O)
   & drawline(O, E)
   & drawline(O, L)
   & drawdashline(A, B)
   & drawdashline(A, E)
   & drawdashline(C, D)
   & drawdashline(A, D)
   & drawdashline(E, C)
   & drawdashsegment(I, G)
   & drawdashsegment(J, H)
   & prooflevel(1)) 
 => 
   collinear(O, E, D))).
