% ------------  TPTP/fof translation by Predrag Janicic, 2025.  ------------
% Input: tmp_2_thm_0930_NinePointsCircleExists.p; Output: thm_0930_NinePointsCircleExists.p; Arg: [-p]

include('geo.ax').
fof(thm, conjecture, ! [ A,B,C,D,E,F] : ((
   dimensions(110, 110)
   & freepoint(A, 20, 20)
   & freepoint(B, 90, 20)
   & freepoint(C, 80, 100)
   & foot(D, A, B, C)
   & foot(E, B, A, C)
   & foot(F, C, A, B)
   & midpoint(G, A, B)
   & midpoint(J, B, C)
   & midpoint(I, C, A)
   & intersection(A, D, B, E, H)
   & midpoint(K, A, H)
   & midpoint(L, B, H)
   & midpoint(M, C, H)
   & intersection(K, J, G, M, O)
   & drawcircle(O, G)
   & drawdashline(K, J)
   & drawdashline(G, M)
   & cmark_b(A)
   & cmark_b(B)
   & cmark_t(C)
   & cmark_r(D)
   & cmark_l(E)
   & cmark_b(F)
   & cmark_b(G)
   & cmark_lb(H)
   & cmark_t(I)
   & cmark_r(J)
   & cmark_lb(M)
   & cmark_b(K)
   & cmark_t(L)
   & cmark_t(O)
   & drawsegment(A, B)
   & drawsegment(A, C)
   & drawsegment(B, C)
   & drawsegment(A, D)
   & drawsegment(B, E)
   & drawsegment(C, F)
   & prooflevel(1)) 
 => 
   perpendicular(G, M, G, E))).
