% ------------  TPTP/fof translation by Predrag Janicic, 2025.  ------------
% Input: tmp_2_thm_0243_Example46.p; Output: thm_0243_Example46.p; Arg: [-p]

include('geo.ax').
fof(thm, conjecture, ! [ A,E,B] : ((
   dimensions(130, 100)
   & freepoint(A, 20, 20)
   & freepoint(E, 80, 20)
   & freepoint(B, 95, 70)
   & collinear(C, A, E)
   & parallel(P1, B, A, E)
   & parallel(P2, A, B, E)
   & intersection(P1, B, P2, A, D)
   & collinear(F, D, B)
   & intersection(C, D, A, F, M)
   & intersection(E, F, B, C, N)
   & intersection(M, N, P2, A, P)
   & intersection(M, N, B, E, Q)
   & cmark_b(A)
   & cmark_b(E)
   & cmark_t(B)
   & cmark_t(D)
   & cmark_b(C)
   & cmark_t(F)
   & cmark_rb(M)
   & cmark_rb(N)
   & cmark_lt(P)
   & cmark_rb(Q)
   & drawsegment(A, E)
   & drawsegment(E, B)
   & drawsegment(B, D)
   & drawsegment(D, A)
   & drawdashsegment(D, C)
   & drawdashsegment(A, F)
   & drawdashsegment(E, F)
   & drawdashsegment(C, B)
   & drawline(P, Q)
   & prooflevel(1)) 
 => 
   sratio(A, P, Q, B) = 1)).
