% ------------  TPTP/fof translation by Predrag Janicic, 2025.  ------------
% Input: tmp_2_thm_0225_Example25.p; Output: thm_0225_Example25.p; Arg: [-p]

include('geo.ax').
fof(thm, conjecture, ! [ A,B,C] : ((
   dimensions(150, 110)
   & freepoint(A, 20, 20)
   & freepoint(B, 70, 20)
   & freepoint(C, 60, 70)
   & collinear(F, A, B)
   & collinear(D, B, C)
   & intersection(F, D, A, C, E)
   & midpoint(P, E, F)
   & midpoint(Q, F, D)
   & midpoint(R, D, E)
   & intersection(A, P, B, C, X)
   & intersection(B, Q, A, C, Y)
   & intersection(C, R, A, B, Z)
   & drawdashline(X, Y)
   & cmark_lb(X)
   & cmark_t(Y)
   & cmark_b(Z)
   & cmark_r(P)
   & cmark_l(Q)
   & cmark_r(R)
   & cmark_t(E)
   & cmark_b(F)
   & cmark_r(D)
   & cmark_b(A)
   & cmark_b(B)
   & cmark_t(C)
   & drawsegment(A, P)
   & drawsegment(B, Y)
   & drawsegment(C, Z)
   & drawsegment(A, Z)
   & drawsegment(C, B)
   & drawsegment(A, E)
   & drawsegment(F, E)
   & prooflevel(1)) 
 => 
   collinear(X, Y, Z))).
