name: build

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites-ubuntu
      run: sudo apt update && sudo apt install build-essential swi-prolog-full xvfb zip
    - name: prerequisites-snap
      run: sudo snap install geogebra-discovery
    - name: test-geogebra
      run: xvfb-run -a -s "-screen 0 1024x768x24" ./test-geogebra.sh
