name: build

on: [push]

jobs:
  check-prolog-ggb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites-ubuntu
      run: sudo apt update && sudo apt install build-essential swi-prolog-full xvfb zip
    - name: prerequisites-snap
      run: sudo snap install geogebra-discovery
    - name: test-geogebra
      run: xvfb-run -a -s "-screen 0 1024x768x24" ./test-geogebra.sh

  check-cpp-ggb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites-ubuntu
      run: sudo apt update && sudo apt install build-essential flex bison libzip-dev zipcmp zipmerge ziptool xvfb
    - name: prerequisites-snap
      run: sudo snap install geogebra-discovery
    - name: test-c++
      run: |
        cd Tools/ADG-Lib_filters/c++
        mkdir build
        cd build
        cmake ..
        make
    - name: test-geogebra
      run: xvfb-run -a -s "-screen 0 1024x768x24" ./test-geogebra-cpp.sh
